
export enum GameView {
  LANDING,
  MENU,
  CHARACTER_CREATION,
  DASHBOARD,
  SCAM_SELECTION,
  VICTIM_DOSSIER,
  ACTIVE_SCAM,
  SCAM_RESULT, 
  SHOP,
  SKILL_TREE,
  GAME_OVER
}

export interface PlayerAttributes {
  name: string;
  gender: string;
  age: string;
  country: string;
  archetype: string;
  clothing: string;
  facialFeatures: string;
  accessories: string;
  avatarUrl: string;
}

export interface CountryStats {
  id: string;
  name: string;
  description: string;
  perkName: string;
  perkDescription: string;
  weaknessName: string;
  weaknessDescription: string;
  startingMoney: number;
  startingThreat: number;
  startingItems: string[];
  startingSkills: string[];
  modifiers: {
    trustBonus?: number;
    threatMultiplier?: number;
    payoutMultiplier?: number;
    suspicionStart?: number;
  };
}

export interface PlayerState {
  attributes: PlayerAttributes;
  money: number;
  threatLevel: number; // 0-100
  scamsCompleted: number;
  inventory: string[];
  skills: string[];
}

export interface Victim {
  id: string;
  name: string;
  age: number;
  gender: 'male' | 'female'; // Added for TTS voice selection
  difficulty: 'easy' | 'medium' | 'hard';
  avatarUrl: string; // Generated by AI
  occupation: string;
  personality: string;
  hiddenFact: string; // Revealed by skills or conversation
  weakness: string;
  resistanceStyle: string; // New: Determines how they fight back (e.g. "Dumb", "Aggressive", "Bureaucratic")
}

export interface ChatMessage {
  sender: 'player' | 'victim' | 'system';
  text: string;
  timestamp: number;
}

export interface ScamState {
  victim: Victim;
  category: string; // e.g., "Grandson in Trouble", "IRS"
  winCondition: string; // New: Specific goal to win
  history: ChatMessage[];
  trust: number; // 0-100
  suspicion: number; // 0-100
  progress: number; // 0-100 (Completion %)
  status: 'active' | 'success' | 'failed' | 'police_called';
  revealedFacts: string[];
}

export interface ArbiterResponse {
  logicScore: number; // 0-100
  emotionalImpact: number; // 0-100
  trustDelta: number;
  suspicionDelta: number;
  progressDelta: number;
  internalThought: string;
  scamStatus: 'continue' | 'success' | 'failed' | 'police_called';
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  cost: number;
  icon: string;
  category: 'social' | 'tech' | 'ops';
}

export interface ShopItem {
  id: string;
  name: string;
  description: string;
  cost: number;
  effect: string;
  icon: string;
}
